import { Table } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import useSWRInfinite from "swr/immutable";
import axios from "axios";
import { LoadingOverlay, Button, Group } from "@mantine/core";

const Home: NextPage = () => {
  const fetcher = async (url: string) => {
    const { data } = await axios.get(url);
    return data;
  };
  const { data, error } = useSWRInfinite("http://localhost:3000", fetcher);
  if (!data) return <LoadingOverlay visible={true} />;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold text-red-500 underline">{data}</h1>
      <Table>
        <thead>
          <tr>
            <th>完了</th>
            <th>Todo</th>
            <th>期日</th>
            <th>重要度</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>aaa</td>
            <td>aaa</td>
            <td>aaa</td>
            <td>aaa</td>
          </tr>
        </tbody>
      </Table>
    </div>
  );
};

export default Home;
